server:
    port: 8443
    ssl:
        key-store: file:///Users/chungpinglee/Documents/workspace-sts-3.9.4.RELEASE/Spring-in-Action-5-Sample-Code/Chapter5/src/main/resources/mykeys.jks
        key-store-password: letmein
        key-password: letmein

