server:
  port: 8443
  ssl:
    key-store: file:///Users/chungpinglee/Documents/workspace-sts-3.9.4.RELEASE/Spring-in-Action-5-Sample-Code/Chapter5/src/main/resources/mykeys.jks
    key-store-password: letmein
    key-password: letmein

logging:
  path: /var/logs/
  file: TacoCloud.log
  level:
    root: WARN
    org.springframework.security: WARN
    org.springframework.jdbc: DEBUG
    javax.persistence: WARN
    org.hibernate: WARN
    tacos: DEBUG

  taco:
   orders:
    pageSize: 14

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taco?useSSL=false&allowPublicKeyRetrieval=true
    username: springuser
    password: letmein

  jpa.hibernate.ddl-auto: update
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  jpa.show-sql: true

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username: springuser
    password: letmein

  jpa.hibernate.ddl-auto: update

logging:
  level:
    tacos: WARN
